Update patch set 7
Patch Set 7:

For me this fails locally with:

Running org.opendaylight.odlparent.featuretest.SingleFeatureTest
Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 44.051 sec <<< FAILURE! - in org.opendaylight.odlparent.featuretest.SingleFeatureTest
installFeature(org.opendaylight.odlparent.featuretest.SingleFeatureTest)[repoUrl: file:/home/moriarty/src/opendaylight/netconf/features/restconf/features4-restc
onf/target/feature/feature.xml, Feature: odl-mdsal-apidocs 1.5.0.SNAPSHOT]  Time elapsed: 8.576 sec  <<< ERROR!
org.ops4j.pax.exam.WrappedTestContainerException: [installFeature(org.opendaylight.odlparent.featuretest.SingleFeatureTest): Unable to resolve root: missing req
uirement [root] osgi.identity; osgi.identity=odl-mdsal-apidocs; type=karaf.feature; version="[1.5.0.SNAPSHOT,1.5.0.SNAPSHOT]"; filter:="(&(osgi.identity=odl-mds
al-apidocs)(type=karaf.feature)(version>=1.5.0.SNAPSHOT)(version<=1.5.0.SNAPSHOT))" [caused by: Unable to resolve odl-mdsal-apidocs/1.5.0.SNAPSHOT: missing requ
irement [odl-mdsal-apidocs/1.5.0.SNAPSHOT] osgi.identity; osgi.identity=odl-restconf; type=karaf.feature; version="[1.5.0.SNAPSHOT,1.5.0.SNAPSHOT]" [caused by:
Unable to resolve odl-restconf/1.5.0.SNAPSHOT: missing requirement [odl-restconf/1.5.0.SNAPSHOT] osgi.identity; osgi.identity=odl-restconf-noauth; type=karaf.fe
ature; version="[1.5.0.SNAPSHOT,1.5.0.SNAPSHOT]" [caused by: Unable to resolve odl-restconf-noauth/1.5.0.SNAPSHOT: missing requirement [odl-restconf-noauth/1.5.
0.SNAPSHOT] osgi.identity; osgi.identity=org.opendaylight.netconf.sal-rest-connector; type=osgi.bundle; version="[1.5.0.SNAPSHOT,1.5.0.SNAPSHOT]"; resolution:=m
andatory [caused by: Unable to resolve org.opendaylight.netconf.sal-rest-connector/1.5.0.SNAPSHOT: missing requirement [org.opendaylight.netconf.sal-rest-connec
tor/1.5.0.SNAPSHOT] osgi.wiring.package; filter:="(osgi.wiring.package=javax.annotation.meta)"]]]]]
        at org.apache.felix.resolver.ResolutionError.toException(ResolutionError.java:42)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:235)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:158)
        at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:216)
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:263)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1176)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:1074)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Patch-set: 7
Label: Verified=0