Add missing slf4j-api dependency to testtool
This depenency was removed and causing:
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory

Change-Id: Ie20b156d484055a8f0325f9047c284defbf95a32
Signed-off-by: Peter Suna <peter.suna@pantheon.tech>