Update patch set 5
Patch Set 5:

> Patch Set 5:
> 
> > Patch Set 5:
> > 
> > We find out problem with call:
> > 127.0.0.1:8181/rests/data/network-topology:network-topology/topology=topology-netconf?content=nonconfig&fields=node(node-id)
> > 
> > 	<h2>HTTP ERROR 500</h2>
> > 	<p>Problem accessing /rests/data/network-topology:network-topology/topology=topology-netconf. Reason:
> > 		<pre>    Request failed.</pre>
> 
> in karaf.log:
> 2020-07-02T15:36:56,499 | WARN  | qtp253609404-275 | HttpChannel                      | 163 - org.eclipse.jetty.util - 9.4.18.v20190429 | /rests/data/network-topology:network-topology/topology=topology-netconf
> javax.servlet.ServletException: javax.servlet.ServletException: java.lang.UnsupportedOperationException: Augmentation node has no QName
>         at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:88) ~[?:?]
>         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) ~[160:org.eclipse.jetty.server:9.4.18.v20190429]
>         at org.eclipse.jetty.server.Server.handle(Server.java:505) ~[160:org.eclipse.jetty.server:9.4.18.v20190429]
>         at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370) [160:org.eclipse.jetty.server:9.4.18.v20190429]
>         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267) [160:org.eclipse.jetty.server:9.4.18.v20190429]
>         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305) [152:org.eclipse.jetty.io:9.4.18.v20190429]
>         at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [152:org.eclipse.jetty.io:9.4.18.v20190429]
>         at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) [152:org.eclipse.jetty.io:9.4.18.v20190429]
>         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698) [163:org.eclipse.jetty.util:9.4.18.v20190429]
>         at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804) [163:org.eclipse.jetty.util:9.4.18.v20190429]
>         at java.lang.Thread.run(Thread.java:834) [?:?]
> Caused by: javax.servlet.ServletException: java.lang.UnsupportedOperationException: Augmentation node has no QName
>         at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:489) ~[?:?]
>         at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427) ~[?:?]
>         at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388) ~[?:?]
>         at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341) ~[?:?]
>         at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228) ~[?:?]
> ...
>                 at org.opendaylight.restconf.nb.rfc8040.jersey.providers.NormalizedNodeJsonBodyWriter.writeTo(NormalizedNodeJsonBodyWriter.java:91) ~[?:?]
>                 at org.opendaylight.restconf.nb.rfc8040.jersey.providers.NormalizedNodeJsonBodyWriter.writeTo(NormalizedNodeJsonBodyWriter.java:50) ~[?:?]

Can we get this rebased? the error above looks a lot like:
  https://jira.opendaylight.org/browse/NETCONF-696

and just FYI in case you notice CSIT failures, the fix for 696 created a regression we
are tracking here:
  https://jira.opendaylight.org/browse/NETCONF-702

Patch-set: 5
Reviewer: Gerrit User 2264 <2264@7fc14799-209e-464c-9743-7a06c2c21a81>